---
provisioner:
  name: chef_solo
  attributes:
    omnibus_updater:
      disabled: true

suites:
  - name: default
    run_list:
      - apt::default
      - recipe[haskell-platform::default]
  - name: justhub
    run_list:
      - apt::default
      - recipe[haskell-platform::default]
    attributes:
      haskell-platform:
        repo_source: justhub
  - name: justhub-version
    run_list:
      - apt::default
      - recipe[haskell-platform::default]
    excludes:
      - ubuntu-12.04
    attributes:
      haskell-platform:
        repo_source: justhub
        version: 1-4.0.el6
