---
driver_config:
  openstack_username: <%= ENV['OS_USERNAME'] %>
  openstack_api_key: <%= ENV['OS_PASSWORD'] %>
  openstack_auth_url: <%= ENV['OS_AUTH_URL'] %>
  key_name: <%= ENV['OS_SSH_KEYPAIR'] %>
  private_key_path: <%= ENV['OS_PRIVATE_SSH_KEY'] %>
  public_key_path: <%= ENV['OS_PUBLIC_SSH_KEY'] %>
  openstack_tenant: <%= ENV['OS_TENANT'] %>
  floating_ip: <%= ENV['OS_FLOATING_IP'] %>
  flavor_ref: <%= ENV['OS_FLAVOR_REF'] %>

provisioner:
  name: chef_solo
  attributes:
    authorization:
      sudo:
        users:
          - vagrant
          - centos
          - ubuntu
    omnibus_updater:
      disabled: true

platforms:
- name: centos-6.5
  driver_plugin: openstack
  driver_config:
    username: centos
    image_ref: "CentOS 6.5"
- name: ubuntu-12.04
  driver_plugin: openstack
  driver_config:
    username: ubuntu
    image_ref: "Ubuntu 12.04"

suites:
  - name: default
    run_list:
      - apt::default
      - recipe[haskell-platform::default]
  - name: justhub
    run_list:
      - apt::default
      - recipe[haskell-platform::default]
    attributes:
      haskell-platform:
        repo_source: "justhub"
  - name: justhub-version
    run_list:
      - apt::default
      - recipe[haskell-platform::default]
    excludes: [ "ubuntu-12.04" ]
    attributes:
      haskell-platform:
        repo_source: "justhub"
        version: "1-4.0.el6"
