---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - apt::default
      - recipe[haskell-platform::default]
    attributes:
  - name: justhub
    run_list:
      - apt::default
      - recipe[haskell-platform::default]
    attributes:
      haskell-platform:
        repo_source: "justhub"
